export const pokemonTypes = new Map<string, string>([
  ['normal', 'normale'],
  ['poison', 'veleno'],
  ['psychic', 'psico'],
  ['grass', 'erba'],
  ['ground', 'terra'],
  ['ice', 'ghiaccio'],
  ['fire', 'fuoco'],
  ['rock', 'roccia'],
  ['dragon', 'drago'],
  ['water', 'acqua'],
  ['bug', 'insetto'],
  ['dark', 'buio'],
  ['fighting', 'lotta'],
  ['ghost', 'spettro'],
  ['steel', 'acciaio'],
  ['flying', 'volante'],
  ['electric', 'elettro'],
  ['fairy', 'folletto'],
]);
